### ISSUE TITLE
Error on Windows 7

### ISSUE THREAD

**Issue by Berrysoft** [conradkleinespel/rpassword#83]
I have tested this crate on Windows 7. The following line causes the error:
https://github.com/conradkleinespel/rpassword/blob/1af683038cd34cd9ffafe614af21f77ff6544e0e/src/lib.rs#L206

Suggested:
``` rust
let mut stream = BufReader::new(std::io::stdin());
```

Anyway, you can ignore this issue if you don't want to maintain for the old, unmaintained Windows 7:)

**Comment by conradkleinespel** [comment]
Hello @Berrysoft, thanks for your report. I'm not sure your suggestion would work as expected because we knowingly use a handle, which we [configure with these lines](https://github.com/conradkleinespel/rpassword/blob/1af683038cd34cd9ffafe614af21f77ff6544e0e/src/lib.rs#L190-L199). But I don't use Windows a lot so I'm not sure. This project has few maintainers and our time is limited so you'll most likely have to find a fix and submit a PR with test case if you need this to work as expected.

**Comment by Berrysoft** [comment]
Yes, I understand the configuration. The code doesn't work on Windows 7 because `CreateFileA` returns a handle `0x3` or `0x1f` in the console, and `NtReadFile` doesn't accept these handles.

It's painful to debug on Windows 7, and I just tested my project in the hypervisor for fun. I cannot be responsible for the change because I'm not able to test all possible cases of this crate. It's OK to ignore this issue.
