### ISSUE TITLE
[BUG?] "No such device or address" on hardened system

### ISSUE THREAD

**Issue by Arthurdw** [conradkleinespel/rpassword#93]
## The issue

Hello, first of all; thank you for maintaining this crate!

I encountered an error when executing `prompt_password` on a securely configured system using [devsec.os_hardening](https://github.com/dev-sec/ansible-collection-hardening/tree/master/roles/os_hardening). The error message is as follows:

```css
Os { code: 6, kind: Uncategorized, message: "No such device or address" }
```

Do you have any insights into why this might be happening?

### System info

`/etc/os-release`
```env
PRETTY_NAME="Debian GNU/Linux 12 (bookworm)"
NAME="Debian GNU/Linux"
VERSION_ID="12"
VERSION="12 (bookworm)"
VERSION_CODENAME=bookworm
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```
`uname -a`
```
Linux <host> 6.1.0-9-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.27-1 (2023-05-08) x86_64 GNU/Linux
```

**Comment by conradkleinespel** [comment]
Hello @Arthurdw ! You're welcome, I appreciate your kind words.

By default, `prompt_password` prompts and reads from `/dev/tty` ([see here](https://github.com/conradkleinespel/rpassword/blob/0f91e8636b81cc34e180789670704e4bed713291/src/lib.rs#L117)). And I see the playbook you're referring to seems to do things on TTYs.

You may need a specific TTY configuration or read from `stdin`, instead of TTY, using this version of `prompt_password`: https://docs.rs/rpassword/latest/rpassword/fn.prompt_password_from_bufread.html

The documentation says "Prompts on the TTY ..." but it's outdated, you can prompt from anything that implements `Write` as the function signature suggests.

Let me know what works for you, I will update the documentation accordingly.

Cheers

**Comment by conradkleinespel** [comment]
And thanks for your feedback, sounds good !
